### ISSUE TITLE
Work out and document how to run individual behave/BDD tests

### ISSUE THREAD

**Issue by nlhkabu** [nlhkabu/connect#29]

**Comment by hjwp** [comment]
In normal behave, you can use `--name` to select features that match a name ([docs](https://pythonhosted.org/behave/behave.html)), and according to the [django-behave docs](https://github.com/django-behave/django-behave) you can pass options to behave via the test runner by prefixing them with `--behave_`, so I think the answer is, eg:

    python manage.py test bdd --behave_name=login

Just testing this out now.  another Useful option is `--behave_stop`, which stops on first failure.  Will do a PR adding instructions to the readme if it all looks good...

**Comment by hjwp** [comment]
Hm, no luck.  `--behave_stop` does work though, so that saves some time...

**Comment by nlhkabu** [comment]
Thanks @hjwp. I got it working with:
    
    manage.py test bdd --behave_name login

It would be nice to be able to run them at scenario level, but I can't see that there would be any way to do that.

**Comment by nlhkabu** [comment]
Bizarre.  When I run this command, it runs only the login scenarios:

    manage.py test bdd --behave_name login

But, when I run any other features ... eg ...

    manage.py test bdd --behave_name logout

... it skips all of the tests.  I have tried several other features, all with the same result.

What could it be that causes the test runner to identify the login scenarios, but not the others?

**Comment by hjwp** [comment]
I'm seeing that too.  Also seeing that, if you try and use `--behave_name=thing` instead of `--behave_name thing`, it just always runs all the tests.

There is always the enticing rabbit-hole that is py.test... [pytest-bdd](https://github.com/pytest-dev/pytest-bdd) + [pytest-django](https://pytest-django.readthedocs.org/en/latest/tutorial.html) might do what we want...

**Comment by hjwp** [comment]
Ah.  I think

    python manage.py test bdd --behave_include login

and

    python manage.py test bdd --behave_include logout

work.  Maybe that'll do for now?

**Comment by nlhkabu** [comment]
Perfect! Thanks @hjwp! :+1:

**Comment by hjwp** [comment]
where do you want to document it?  In README.rst?  Or maybe in a new CONTRIBUTING.rst?  Maybe just a new "contributing" section in the README will do for now?

**Comment by hjwp** [comment]
How about #37 ?

**Comment by nlhkabu** [comment]
Yep - I think having this in the README is great for now :dancers:
