### ISSUE TITLE
BDD tests failing against "invalid email" error message

### ISSUE THREAD

**Issue by hjwp** [nlhkabu/connect#33]
I see several BDD tests currently failing to find the correct "invalid email" error message.

Instead of seeing "Please enter a valid email address." they see "This value should be a valid email.".  Not sure why as yet.  Somehow the form's custom error message isn't getting through?  Could be something to do with django versions, or internationalization maybe?

Python 3.4.3, Django 1.8.2.

**Comment by hjwp** [comment]
Example failure:

```
Failing scenarios:
  bdd/features/invite_user.feature:23  Moderator submits invalid data to the invite user form -- @1.3 
```
more detail:

```
  Scenario Outline: Moderator submits invalid data to the invite user form -- @1.3   # bdd/features/invite_user.feature:23
    Given there is a standard user in the database                                   # bdd/features/steps/common.py:10 0.001s
    And there is a moderator in the database                                         # bdd/features/steps/common.py:36 0.020s
    And I am logged in as that moderator                                             # bdd/features/steps/common.py:68 0.374s
    Given I am "a logged in moderator"                                               # bdd/features/steps/common.py:83 0.000s
    When I visit the "invite user" page                                              # bdd/features/steps/common.py:91 0.117s
    And I enter "First Last" into the "full name" field                              # bdd/features/steps/common.py:113 0.065s
    And I enter "invalidemail" into the "email" field                                # bdd/features/steps/common.py:113 0.061s
    And I submit the form                                                            # bdd/features/steps/common.py:167 0.053s
    Then I see "Please enter a valid email address."                                 # bdd/features/steps/common.py:209 3.048s
      Assertion Failed: could not find 'Please enter a valid email address.' in page body:
      example.com
      Moderators
      My Account
      Logout
      example.com
      A tagline
      Invite a New Member
      Review Membership Applications
      Review Abuse Reports
      View Logs
      Invite a New Member
      Please provide the details of the member you wish to invite. Once they have accepted your invitatation, they will be able to edit the details provided here.
      Name
      Email
      This value should be a valid email.
      Made with by nlh and contributors. Fork me on Github.
```

**Comment by nlhkabu** [comment]
I have just pushed a fix for this - it has to do with the library (Django Parsley) that is converting the django form error messages to JS errors.  It's not working properly on email addresses, so they are showing default messages.

I have forked the repo in question and made the changes.  I am waiting on a merge, but not holding my breath :)

In the meantime, I have updated the requirements file to point the forked repo.  See: https://github.com/nlhkabu/connect/commit/fd7af147d655b329db706a9da09eae81936ee418

**Comment by hjwp** [comment]
Nice!  Let me update that.  Other than that, I have a full set of passing BDD tests fyi :-) :guitar: :guitar: :guitar:

**Comment by nlhkabu** [comment]
Cheers! :beers:

**Comment by hjwp** [comment]
Hm, that doesn't seem to have worked...

**Comment by nlhkabu** [comment]
We had some issues with pip caching yesterday.  Try running it with `--ignore-installed`

**Comment by hjwp** [comment]
Seems like something magic happened overnight, all tests passing now.  :notes: everything is fixed, at the end of the sprints! :musical_note:

**Comment by nlhkabu** [comment]
:dancer:
