### ISSUE TITLE
IntegrityError at /admin/accounts/customuser/add/

### ISSUE THREAD

**Issue by nlhkabu** [nlhkabu/connect#35]
null value in column "last_login" violates not-null constraint

Error occurs when attempting to manually create a user via the Django admin.

**Comment by nlhkabu** [comment]
https://groups.google.com/forum/#!topic/python-social-auth/S3fxcFyL7fk

**Comment by Natim** [comment]
We should add a default timezone.now on this field

**Comment by nlhkabu** [comment]
This error confuses me because it's not defined on my model - but rather on the AbstractBaseUser that I'm inheriting from.

The solution on that forum is "just run the migrations"... which I have done...

**Comment by Natim** [comment]
You can redefine the field anyway with the default.

**Comment by nlhkabu** [comment]
No - that didn't work - but I did find this https://docs.djangoproject.com/en/1.8/releases/1.8/#abstractuser-last-login-allows-null-values in the 1.8 release notes.
