### ISSUE TITLE
When a moderator reports another user, they should not receive a notification email

### ISSUE THREAD

**Issue by Natim** [nlhkabu/connect#4]

**Comment by nlhkabu** [comment]
Probably a good idea to check all the places in the codebase where moderators are receiving emails to check that they're not getting anything they're not supposed to.
Will need to improve unit tests to cover this too.

**Comment by nlhkabu** [comment]
This is only an issue when the moderator reports another user, not when they are being reporting by another user.

**Comment by nlhkabu** [comment]
Fixed with 5760ff71bd244f9043d57545429318b62d598713

**Comment by Natim** [comment]
Can you point me in the commit above the line that test this behavior please?

**Comment by nlhkabu** [comment]
Whoops.  Wrong commit.  Here it is @Natim:
https://github.com/nlhkabu/connect/commit/8081ff92724c6a3b8b87bdcc1824a28a788b9011
