### ISSUE TITLE
Get coverage working - use coveralls.io

### ISSUE THREAD

**Issue by nlhkabu** [nlhkabu/connect#48]
https://github.com/z4r/python-coveralls

**Comment by Natim** [comment]
Isn't it what we are using already? https://github.com/nlhkabu/connect/blob/master/tox.ini#L7

**Comment by nlhkabu** [comment]
We're using this: https://pypi.python.org/pypi/coverage/
Coveralls.io is a hosted solution, so will need to swap out coverage for python-coveralls.

**Comment by Natim** [comment]
Yes I know both of this tools. Coveralls needs coverage in order to work.

**Comment by nlhkabu** [comment]
Oh... I see...

**Comment by nlhkabu** [comment]
Closed by https://github.com/nlhkabu/connect/commit/26476b5fd69641e077a786b9045e6899057b1ee7
