### ISSUE TITLE
demo user and password does not allow login

### ISSUE THREAD

**Issue by dariushazimi** [nlhkabu/connect#61]
Hi @nlhkabu.

Trying to login as demo but it is not letting me in using the demo account you have specified.

Thanks

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/11768138937996/157626694882787)

**Comment by nlhkabu** [comment]
Hi @dariushazimi!  Thanks for picking up on this.

It looks as though both of the accounts had been edited by people playing around with the logged in users.  I've reset them now, so you should be good to go :)

**Comment by dariushazimi** [comment]
Nice, Login works. thanks.
